catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade

packages:
  - apps/*

catalog:
  '@antfu/eslint-config': ^6.6.1
  '@better-auth/utils': ^0.3.0
  '@eslint-react/eslint-plugin': ^2.3.13
  '@godaddy/terminus': ^4.12.1
  '@hono/node-server': ^1.19.5
  '@hono/zod-openapi': ^1.1.3
  '@noble/hashes': ^2.0.1
  '@radix-ui/react-slot': ^1.2.4
  '@scalar/hono-api-reference': ^0.9.19
  '@tailwindcss/vite': ^4.1.18
  '@types/node': ^25.0.0
  '@types/pg': ^8.15.5
  '@types/react': ^19.2.5
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react-swc': ^4.2.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cross-env: ^10.1.0
  dotenv: ^17.2.3
  dotenv-expand: ^12.0.3
  drizzle-kit: ^0.31.5
  drizzle-orm: ^0.44.5
  drizzle-zod: ^0.8.3
  eslint: ^9.39.1
  eslint-plugin-format: ^1.1.0
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  globals: ^16.5.0
  hono: ^4.9.9
  hono-pino: ^0.10.3
  husky: ^9.1.7
  jose: ^6.1.3
  lint-staged: ^15.4.3
  lucide-react: ^0.561.0
  pg: ^8.16.3
  pino: ^10.0.0
  react: ^19.2.0
  react-dom: ^19.2.0
  rimraf: ^6.1.2
  stoker: 2.0.1
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tsc-alias: ^1.8.16
  tsx: ^4.20.6
  tw-animate-css: ^1.4.0
  typescript: ^5.7.3
  vite: ^7.2.4
  vitest: ^3.2.4
  zod: ^4.1.11

onlyBuiltDependencies:
  - esbuild
  - '@swc/core'
